### PR TITLE
Add tests for griddb_fdw

### PR DESCRIPTION
**Pull request by tunghdt**

### CODE REVIEW

**Comment by t-kataym** [comment]
I have comments. Could you tell me to help my understanding?

**test.sh**:
There is test.sh in make_check_initializer directory because I have requested when I received the merge request #16.
Is test.sh you created same as test.sh in make_check_initializer directory?
If yes, please modify test.sh make_check_initializer.

**.c file in make_check_initializer**:
There is griddb_init.c. You added griddb_init_core.c and griddb_init_post.c.
You don't modify existing griddb_init.c at all.
What is relationship of these files?

**Comment by tunghdt** [comment]
> **test.sh**:
> There is test.sh in make_check_initializer directory because I have requested when I received the merge request #16.
> Is test.sh you created same as test.sh in make_check_initializer directory?
> If yes, please modify test.sh make_check_initializer.

test.sh in make_check_initializer only prepare for test, do not execute "make check".
test.sh I created will prepare for test and execute "make check". Also "make check" should be executed at the directory of griddb_fdw not in make_check_initializer.

> **.c file in make_check_initializer**:
> There is griddb_init.c. You added griddb_init_core.c and griddb_init_post.c.
> You don't modify existing griddb_init.c at all.
> What is relationship of these files?

About added tests file and **.c files, I only copy them from "FDW Test Improvement" in SVN and write test.sh to execute them. I am not the author of these files. Could you request the author to modify/merge these **.c files?

**Comment by t-kataym** [comment]
Thank you for your reply.

> test.sh I created will prepare for test and execute "make check". 
test.sh you created contains same code as test.sh in make_check_initializer.
I don't think test.sh in top directory is unnecessary because tester should only call test.sh in make_check_initializer and execute "make check".

> Could you request the author to modify/merge these **.c files?
No. The source code for initializing griddb's container has been committed on on GitHub.
Therefore you need to modify(merge) existing file, I think. Could you do that?

**Comment by tunghdt** [comment]
OK I will merge them and create other pull request.
I close this request.

**Pull request closed without merging**
